import { GameSchema } from "../Shared";

const BatterSchema = {
	type: "object",
	required: [
		"last_name",
		"first_name",
		"display_name",
		"position",
		"bat_order",
		"sub_bat_order",
		"sacrifices",
		"at_bats",
		"plate_appearances",
		"singles",
		"doubles",
		"triples",
		"home_runs",
		"sac_flies",
		"sac_hits",
		"stolen_bases",
		"caught_stealing",
		"rbi_with_two_outs",
		"total_bases",
		"runs",
		"hits",
		"rbi",
		"walks",
		"strike_outs",
		"left_on_base",
		"hit_by_pitch",
		"team_abbreviation",
		"ops",
		"avg",
		"obp",
		"slg",
		"at_bats_per_home_run",
		"at_bats_per_rbi",
		"walk_rate",
		"plate_appearances_per_rbi",
		"plate_appearances_per_home_run",
		"extra_base_hits",
		"stolen_base_average",
		"strikeout_rate",
		"ops_string",
		"slg_string",
		"obp_string",
		"avg_string",
		"batting_highlights"
	],
	properties: {
		last_name: { type: "string" },
		first_name: { type: "string" },
		display_name: { type: "string" },
		position: { type: "string" },
		bat_order: { type: "number" },
		sub_bat_order: { type: "number" },
		sacrifices: { type: "number" },
		at_bats: { type: "number" },
		plate_appearances: { type: "number" },
		singles: { type: "number" },
		doubles: { type: "number" },
		triples: { type: "number" },
		home_runs: { type: "number" },
		sac_flies: { type: "number" },
		sac_hits: { type: "number" },
		stolen_bases: { type: "number" },
		caught_stealing: { type: "number" },
		rbi_with_two_outs: { type: "number" },
		total_bases: { type: "number" },
		runs: { type: "number" },
		hits: { type: "number" },
		rbi: { type: "number" },
		walks: { type: "number" },
		strike_outs: { type: "number" },
		left_on_base: { type: "number" },
		hit_by_pitch: { type: "number" },
		team_abbreviation: { type: "string" },
		ops: { type: "number" },
		avg: { type: "number" },
		obp: { type: "number" },
		slg: { type: "number" },
		at_bats_per_home_run: { type: "number" },
		at_bats_per_rbi: { type: "number" },
		walk_rate: { type: "number" },
		plate_appearances_per_rbi: { type: "number" },
		plate_appearances_per_home_run: { type: "number" },
		extra_base_hits: { type: "number" },
		stolen_base_average: { type: "number" },
		strikeout_rate: { type: "number" },
		ops_string: { type: "string" },
		slg_string: { type: "string" },
		obp_string: { type: "string" },
		avg_string: { type: "string" },
		batting_highlights: { type: "string" }
	}
};

const PitcherSchema = {
	type: "object",
	required: [
		"last_name",
		"first_name",
		"display_name",
		"pitch_order",
		"win",
		"loss",
		"save",
		"hold",
		"era",
		"whip",
		"innings_pitched",
		"hits_allowed",
		"runs_allowed",
		"earned_runs",
		"walks",
		"intentional_walks",
		"strike_outs",
		"home_runs_allowed",
		"pitch_count",
		"pitches_strikes",
		"wild_pitches",
		"hit_by_pitch",
		"errors",
		"team_abbreviation"
	],
	properties: {
		last_name: { type: "string" },
		first_name: { type: "string" },
		display_name: { type: "string" },
		pitch_order: { type: "number" },
		win: { type: "boolean" },
		loss: { type: "boolean" },
		save: { type: "boolean" },
		hold: { type: "boolean" },
		era: { type: "number" },
		whip: { type: "number" },
		innings_pitched: { type: "number" },
		hits_allowed: { type: "number" },
		runs_allowed: { type: "number" },
		earned_runs: { type: "number" },
		walks: { type: "number" },
		intentional_walks: { type: "number" },
		strike_outs: { type: "number" },
		home_runs_allowed: { type: "number" },
		pitch_count: { type: "number" },
		pitches_strikes: { type: "number" },
		wild_pitches: { type: "number" },
		hit_by_pitch: { type: "number" },
		errors: { type: "number" },
		team_abbreviation: { type: "string" }
	}
};

const FielderSchema = {
	type: "object",
	required: [
		"last_name",
		"first_name",
		"display_name",
		"errors",
		"team_abbreviation"
	],
	properties: {
		last_name: { type: "string" },
		first_name: { type: "string" },
		display_name: { type: "string" },
		errors: { type: "number" },
		team_abbreviation: { type: "string" }
	}
};

const BatterTotalSchema = {
	type: "object",
	required: [
		"sacrifices",
		"at_bats",
		"plate_appearances",
		"singles",
		"doubles",
		"triples",
		"home_runs",
		"sac_flies",
		"sac_hits",
		"stolen_bases",
		"caught_stealing",
		"rbi_with_two_outs",
		"total_bases",
		"runs",
		"hits",
		"rbi",
		"walks",
		"strike_outs",
		"left_on_base",
		"hit_by_pitch",
		"ops",
		"avg",
		"obp",
		"slg",
		"at_bats_per_home_run",
		"at_bats_per_rbi",
		"walk_rate",
		"plate_appearances_per_rbi",
		"plate_appearances_per_home_run",
		"extra_base_hits",
		"stolen_base_average",
		"strikeout_rate",
		"ops_string",
		"slg_string",
		"obp_string",
		"avg_string",
		"batting_highlights"
	],
	properties: {
		sacrifices: { type: "number" },
		at_bats: { type: "number" },
		plate_appearances: { type: "number" },
		singles: { type: "number" },
		doubles: { type: "number" },
		triples: { type: "number" },
		home_runs: { type: "number" },
		sac_flies: { type: "number" },
		sac_hits: { type: "number" },
		stolen_bases: { type: "number" },
		caught_stealing: { type: "number" },
		rbi_with_two_outs: { type: "number" },
		total_bases: { type: "number" },
		runs: { type: "number" },
		hits: { type: "number" },
		rbi: { type: "number" },
		walks: { type: "number" },
		strike_outs: { type: "number" },
		left_on_base: { type: "number" },
		hit_by_pitch: { type: "number" },
		ops: { type: "number" },
		avg: { type: "number" },
		obp: { type: "number" },
		slg: { type: "number" },
		at_bats_per_home_run: { type: "number" },
		at_bats_per_rbi: { type: "number" },
		walk_rate: { type: "number" },
		plate_appearances_per_rbi: { type: "number" },
		plate_appearances_per_home_run: { type: "number" },
		extra_base_hits: { type: "number" },
		stolen_base_average: { type: "number" },
		strikeout_rate: { type: "number" },
		ops_string: { type: "string" },
		slg_string: { type: "string" },
		obp_string: { type: "string" },
		avg_string: { type: "string" },
		batting_highlights: { type: "string" }
	}
};

export const MlbGameDataSchema = {
	type: "object",
	required: [
		"league",
		"away_period_scores",
		"home_period_scores",
		"officials",
		"event_information",
		"away_team",
		"home_team",
		"away_errors",
		"home_errors",
		"away_batters",
		"home_batters",
		"away_pitchers",
		"home_pitchers",
		"away_fielding",
		"home_fielding",
		"away_batter_totals",
		"home_batter_totals"
	],
	properties: {
		...GameSchema,
		away_errors: { type: "number" },
		home_errors: { type: "number" },
		away_batters: { type: "array", items: BatterSchema },
		home_batters: { type: "array", items: BatterSchema },
		away_pitchers: { type: "array", items: PitcherSchema },
		home_pitchers: { type: "array", items: PitcherSchema },
		away_fielding: { type: "array", items: FielderSchema },
		home_fielding: { type: "array", items: FielderSchema },
		away_batter_totals: BatterTotalSchema,
		home_batter_totals: BatterTotalSchema,
	}
};