version: "3.7"
services:
  barstool-database-container:
    container_name: barstool-database-container
    image: postgres
    restart: unless-stopped
    volumes:
        - ./data/db:/var/lib/postgresql/data
    env_file:
        - database.env
    ports:
      - "6666:5432"
    expose:
      - 6666
    networks:
      - barstool-database-network
networks:
  barstool-database-network:
    driver: bridge