export const NBATeamColors = [
	{ name: "Atlanta Hawks", hex: "#E03A3E" },
	{ name: "Boston Celtics", hex: "#007A33" },
	{ name: "Brooklyn Nets", hex: "#000000" },
	{ name: "Charlotte Hornets", hex: "#1D1160" },
	{ name: "Chicago Bulls", hex: "#CE1141" },
	{ name: "Cleveland Cavaliers", hex: "#860038" },
	{ name: "Dallas Mavericks", hex: "#00538C" },
	{ name: "Denver Nuggets", hex: "#0E2240" },
	{ name: "Detroit Pistons", hex: "#C8102E" },
	{ name: "Golden State Warriors", hex: "#1D428A" },
	{ name: "Houston Rockets", hex: "#CE1141" },
	{ name: "Indiana Pacers", hex: "#002D62" },
	{ name: "Los Angeles Clippers", hex: "#C8102E" },
	{ name: "Los Angeles Lakers", hex: "#552583" },
	{ name: "Memphis Grizzlies", hex: "#5D76A9" },
	{ name: "Miami Heat", hex: "#98002E" },
	{ name: "Milwaukee Bucks", hex: "#00471B" },
	{ name: "Minnesota Timberwolves", hex: "#0C2340" },
	{ name: "New Orleans Pelicans", hex: "#0C2340" },
	{ name: "New York Knicks", hex: "#006BB6" },
	{ name: "Oklahoma City Thunder", hex: "#007AC1" },
	{ name: "Orlando Magic", hex: "#0077C0" },
	{ name: "Philadelphia 76ers", hex: "#006BB6" },
	{ name: "Phoenix Suns", hex: "#1D1160" },
	{ name: "Portland Trail Blazers", hex: "#E03A3E" },
	{ name: "Sacramento Kings", hex: "#5A2D81" },
	{ name: "San Antonio Spurs", hex: "#C4CED4" },
	{ name: "Toronto Raptors", hex: "#CE1141" },
	{ name: "Utah Jazz", hex: "#002B5C" },
	{ name: "Washington Wizards", hex: "#002B5C" }
];