export const NBATeamColors = [
	{ name: "Atlanta Hawks", hex: "#E03A3E" },
	{ name: "Boston Celtics", hex: "#007A33" },
	{ name: "Brooklyn Nets", hex: "#000000" },
	{ name: "Charlotte Hornets", hex: "#1D1160" },
	{ name: "Chicago Bulls", hex: "#CE1141" },
	{ name: "Cleveland Cavaliers", hex: "#860038" },
	{ name: "Dallas Mavericks", hex: "#00538C" },
	{ name: "Denver Nuggets", hex: "#0E2240" },
	{ name: "Detroit Pistons", hex: "#C8102E" },
	{ name: "Golden State Warriors", hex: "#1D428A" },
	{ name: "Houston Rockets", hex: "#CE1141" },
	{ name: "Indiana Pacers", hex: "#002D62" },
	{ name: "Los Angeles Clippers", hex: "#C8102E" },
	{ name: "Los Angeles Lakers", hex: "#552583" },
	{ name: "Memphis Grizzlies", hex: "#5D76A9" },
	{ name: "Miami Heat", hex: "#98002E" },
	{ name: "Milwaukee Bucks", hex: "#00471B" },
	{ name: "Minnesota Timberwolves", hex: "#0C2340" },
	{ name: "New Orleans Pelicans", hex: "#0C2340" },
	{ name: "New York Knicks", hex: "#006BB6" },
	{ name: "Oklahoma City Thunder", hex: "#007AC1" },
	{ name: "Orlando Magic", hex: "#0077C0" },
	{ name: "Philadelphia 76ers", hex: "#006BB6" },
	{ name: "Phoenix Suns", hex: "#1D1160" },
	{ name: "Portland Trail Blazers", hex: "#E03A3E" },
	{ name: "Sacramento Kings", hex: "#5A2D81" },
	{ name: "San Antonio Spurs", hex: "#C4CED4" },
	{ name: "Toronto Raptors", hex: "#CE1141" },
	{ name: "Utah Jazz", hex: "#002B5C" },
	{ name: "Washington Wizards", hex: "#002B5C" }
];

export const MlbTeamColors = [
	{ name: "Boston Red Sox", hex: "#bd3039" },
	{ name: "San Francisco Giants", hex: "#fd5a1e" },
	{ name: "Chicago Cubs", hex: "#0e3386" },
	{ name: "St. Louis Cardinals", hex: "#c41e3a" },
	{ name: "Detroit Tigers", hex: "#182d55" },
	{ name: "New York Yankees", hex: "#132448" },
	{ name: "Texas Rangers", hex: "#003278" },
	{ name: "Arizona Diamondbacks", hex: "#a71930" },
	{ name: "Atlanta Braves", hex: "#13274f" },
	{ name: "Baltimore Orioles", hex: "#df4601" },
	{ name: "Chicago White Sox", hex: "#000000" },
	{ name: "Cincinnati Reds", hex: "#c6011f" },
	{ name: "Cleveland Indians", hex: "#e31937" },
	{ name: "Colorado Rockies", hex: "#33006f" },
	{ name: "Houston Astros", hex: "#002d62" },
	{ name: "Kansas City Royals", hex: "#174885" },
	{ name: "Los Angeles Angels", hex: "#ba0021" },
	{ name: "Miami Marlins", hex: "#ff6600" },
	{ name: "Milwaukee Brewers", hex: "#0a2351" },
	{ name: "Minnesota Twins", hex: "#002b5c" },
	{ name: "New York Mets", hex: "#002d72" },
	{ name: "Oakland Athletics", hex: "#003831" },
	{ name: "Philadelphia Phillies", hex: "#e81828" },
	{ name: "Pittsburgh Pirates", hex: "#fdb827" },
	{ name: "San Diego Padres", hex: "#002d62" },
	{ name: "Seattle Mariners", hex: "#0c2c56" },
	{ name: "Tampa Bay Rays", hex: "#092c5c" },
	{ name: "Toronto Blue Jays", hex: "#134a8e" },
	{ name: "Washington Nationals", hex: "#ab0003" }
];