version: "3.2"
services:
 redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    env_file:
      - .env
    restart:
      always
    networks:
      - barstool-database-network
networks:
  barstool-database-network:
    driver: bridge